In [1]:
# Example 1: Basic 1D Array Creation
import numpy
a = numpy.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [2]:
# Example 2: Using np alias
import numpy as np
a = np.array([10,20,30,40,50])
print(a) 

[10 20 30 40 50]


In [3]:
# Example 3: Using from numpy import *
from numpy import *
a=array([10, 20,30,40,50])
print(a)

[10 20 30 40 50]


In [4]:
# Example 4: Array with mixed data types (converts to float)
from numpy import array
a = array([10,30,40.5, 50,100])
print(a)

[ 10.   30.   40.5  50.  100. ]


In [5]:
# Example 5: Creating evenly spaced array
import numpy as np
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
# Example 6: Different arange() usage
import numpy as np
a = np.arange(10)
b = np.arange(5,10)
c = np.arange(10,1,-1)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[10  9  8  7  6  5  4  3  2]


In [7]:
# Example 7: Creating arrays with zeros and ones
import numpy as np
K = np.zeros(5)
R = np.ones(5)
print(K)
print(R)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [8]:
# Example 8: Basic mathematical operations
import numpy as np
K = np.array([10, 20, 30, 40,50])

K = K+5
print(K)
K = K-5
print(K)
K = K*5
print(K)
K = K/5
print(K)


[15 25 35 45 55]
[10 20 30 40 50]
[ 50 100 150 200 250]
[10. 20. 30. 40. 50.]


In [9]:
# Example 9: Aliasing arrays (reference)
import numpy as np
k = np.array([3, 5, 6,7,8])
print(k)
# Give another name h to array k
h = k
print(h)
print(k)
k[0] = 45
print(h)
print(k)

[3 5 6 7 8]
[3 5 6 7 8]
[3 5 6 7 8]
[45  5  6  7  8]
[45  5  6  7  8]


In [10]:
# Example 10: Using copy() method
import numpy as np
k = np.array([3,5,6,7,8])
print(k)
# Create a copy of array k and call it h
h = k.copy()
print(h)
print(k)
k[0] = 45
print(h)
print(k)

[3 5 6 7 8]
[3 5 6 7 8]
[3 5 6 7 8]
[3 5 6 7 8]
[45  5  6  7  8]


In [11]:
# Example 11: Creating 2D array
import numpy as np
x = np.array([[2,4,6],[6,8,10]])
print(x)

[[ 2  4  6]
 [ 6  8 10]]


In [12]:
# Example 12: ndim attribute (number of dimensions)
import numpy as np
A = np.array([5,6,7,8])
R = np.array([[4,5,6],[7,8,9]])
print(A.ndim)  # Number of dimensions in array A
print(R.ndim)  # Number of dimensions in array R

1
2


In [13]:
# Example 13: shape attribute
import numpy as np
k = np.array([1,2,3,4,5])
print(k.shape)  # Number of elements in array k
d = np.array([[5,6,7],[7,8,9]])
print(d.shape)  # Number of rows and columns in array d

(5,)
(2, 3)


In [14]:
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1.size)  # Total number of element

5


In [15]:
# For 2D array
import numpy as np
k = np.array([[5,6,7],[7,8,9]])
print(k.size)  # Total elements (rows * columns)

6


In [16]:
# Example 15: itemsize attribute
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1.itemsize)  # Memory size of array elements in bytes

8


In [17]:
# Example 16: Reshaping arrays
import numpy as np
d = np.array([[4,5,6,7],[5,6,7,8],[7,8,9,6]])
print(d)
# Reshape array d to 6 rows and 2 columns
d = d.reshape(6,2)
print(d)
# Reshape array d to 1 row and 12 columns
d = d.reshape(1,12)
print(d)
# Reshape array d to 12 rows and 1 column
d = d.reshape(12,1)
print(d)

[[4 5 6 7]
 [5 6 7 8]
 [7 8 9 6]]
[[4 5]
 [6 7]
 [5 6]
 [7 8]
 [7 8]
 [9 6]]
[[4 5 6 7 5 6 7 8 7 8 9 6]]
[[4]
 [5]
 [6]
 [7]
 [5]
 [6]
 [7]
 [8]
 [7]
 [8]
 [9]
 [6]]


In [18]:
# Example 17: Creating empty arrays
import numpy as np
x = np.empty([3,2], dtype = int)
y = np.empty([4,4], dtype = float)
print(x)
print(y)

[[5 6]
 [7 7]
 [8 9]]
[[4.67296746e-307 1.69121096e-306 4.00535364e-307 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 1.33504432e-306]]


In [19]:
# Example 18: Creating identity matrix
import numpy
a = numpy.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# Example 19: zeros() function for 2D
import numpy
Q = numpy.zeros([3,2], dtype = int)
Z = numpy.zeros([4,4], dtype = float)
print(Q)
print(Z)

[[0 0]
 [0 0]
 [0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# Example 20: ones() function for 2D
import numpy
Q = numpy.ones([3,2], dtype = int)
Z = numpy.ones([4,4], dtype = float)
print(Q)
print(Z)

[[1 1]
 [1 1]
 [1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
# Example 21: concatenate() function
import numpy as np
a = np.array([2,3,4,50])
b = np.array([8, 9,10,11,15])
c = np.concatenate([a,b])
print(c)

[ 2  3  4 50  8  9 10 11 15]


In [23]:
# Example 22: concatenate() column-wise
import numpy as np
a = np.array([[2,3,4],[4,5,6],[7,8,9]])
b = np.concatenate([a,a], axis=1)  # concatenate array a with array a column wise
print(b)

[[2 3 4 2 3 4]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [24]:
# Example 23: concatenate() row-wise
import numpy as np
a = np.array([[2,3,4],[4,5,6],[7,8,9]])
b = np.concatenate([a,a], axis=0)  # concatenate array a with array a row wise
print(b)

[[2 3 4]
 [4 5 6]
 [7 8 9]
 [2 3 4]
 [4 5 6]
 [7 8 9]]


In [25]:
# Example 24: hstack() - horizontal stacking
import numpy as np
a = np.array([1,2,3])
b = np.array([10,11,12])
c = np.hstack((a,b))
print(c)

[ 1  2  3 10 11 12]


In [26]:
# Example 25: vstack() - vertical stacking
import numpy as np
a = np.array([1,2,3])
b = np.array([10,11,12])
c = np.vstack((a,b))
print(c)

[[ 1  2  3]
 [10 11 12]]


In [27]:
# Example 26: split() function
import numpy as np
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # split array into 3 subsets like- [0 : 3], [3 : 5] and [5 : ]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [28]:
# Example 27: hsplit() - horizontal splitting
import numpy as np
a = np.arange(16).reshape((4, 4))
print(a)
left, right = np.hsplit(a, 2)
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [29]:
# Example 28: vsplit() - vertical splitting
import numpy as np
a = np.arange(16).reshape((4, 4))
print(a)
top, bottom = np.vsplit(a, 2)
print(top)
print(bottom)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [30]:
# Example 29: Covariance calculation
import numpy as np
x = np.array([0,1,2])
y = np.array([2,1,0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array2:")
print(y)
print("\nCovariance matrix of the said arrays:\n", np.cov(x, y))


Original array1:
[0 1 2]

Original array2:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [31]:
# Example 30: statistics
import numpy as np

array1 = np.array([[10, 20, 30], [40, 50, 60]])

print("Mean: ", np.mean(array1))       # Avg of all elements
print("Std: ", np.std(array1))         # Standard deviation
print("Var: ", np.var(array1))         # Variance
print("Sum: ", np.sum(array1))         # Sum of all elements
print("Prod: ", np.prod(array1))       # Product of all elements

Mean:  35.0
Std:  17.07825127659933
Var:  291.6666666666667
Sum:  210
Prod:  720000000
