In [1]:
import torch
import numpy as np

# Create tensor directly from data (list of lists)
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# Create tensor from a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [2]:
# Create a tensor from another tensor (same shape & dtype)
x_ones = torch.ones_like(x_data)  # fills with 1s
print(f"Ones Tensor: \n{x_ones}\n")

# Create random tensor with same shape, overriding dtype
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n{x_rand}\n")

# Create tensor with specified shape and values
shape = (2, 3)
rand_tensor = torch.rand(shape)    # random values between 0 and 1
ones_tensor = torch.ones(shape)    # all 1s
zeros_tensor = torch.zeros(shape)  # all 0s

print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Ones Tensor: \n{ones_tensor}\n")
print(f"Zeros Tensor: \n{zeros_tensor}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.5492, 0.4933],
        [0.8660, 0.5481]])

Random Tensor: 
tensor([[0.4254, 0.6972, 0.5944],
        [0.4907, 0.4112, 0.2073]])

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



Attributes of a Tensor

In [3]:

tensor = torch.rand(3, 4)  # shape = (3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Oprations on Tensors

In [4]:
# Indexing and slicing 
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# Modify second column to all 0s
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [5]:
#Jointing tensors (concatenate): column dim=1  row dim=0
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"Concatenated Tensor:\n{t1}")

Concatenated Tensor:
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
import torch

tensor = torch.tensor([[1., 2.],
                       [3., 4.],
                       [5., 6.]])
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)  

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

In [7]:

# Element-wise multiplication
z1 = tensor * tensor                 
z2 = tensor.mul(tensor)            
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)   

tensor([[ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])

Single-element Tensor to Python Number

In [18]:

agg = tensor.sum()           # aggregate: sum all elements
agg_item = agg.item()        # convert single-element tensor to Python float
print(agg_item, type(agg_item))


21.0 <class 'float'>


In [9]:
print("Before in-place add:\n", tensor)
tensor.add_(5)  # in-place addition: adds 5 to every element
print("After in-place add:\n", tensor)

Before in-place add:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
After in-place add:
 tensor([[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])


Bridge with NumPy

In [19]:
# Tensor to NumPy array (shares memory)
t = torch.ones(5)
print(f"Tensor t: {t}")
n = t.numpy()
print(f"NumPy n: {n}")

# Change tensor, NumPy reflects change
t.add_(1)
print(f"After t.add_(1), t: {t}")
print(f"n: {n}")

Tensor t: tensor([1., 1., 1., 1., 1.])
NumPy n: [1. 1. 1. 1. 1.]
After t.add_(1), t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [22]:
# NumPy to Tensor (also shares memory)
n = np.ones(5)
t = torch.from_numpy(n)

# Change NumPy array, tensor reflects change
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
