In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

data = pd.read_csv("Iris.csv", header='infer').values
x = data[:, 1:-1]
y = data[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y)
print("Shapes", x_train.shape, y_train.shape, x_test.shape, y_test.shape)

k = int(input("Enter the number of clusters you want to divide your data into (k): "))
n = int(input("Enter the number of iterations: "))  

per = np.random.permutation(x_train.shape[0])
centroid = np.zeros(shape=(k, x_train.shape[1]))

for i in range(k):
    centroid[i, :] = x_train[per[i], :]
print(centroid)

Shapes (120, 4) (120,) (30, 4) (30,)
[[6.3 2.5 4.9 1.5]
 [6.3 3.4 5.6 2.4]
 [7.7 2.6 6.9 2.3]]


In [16]:
for _ in range(n):
    dist = np.zeros(shape=(k, x_train.shape[0]))
    
    for i in range(k):
        dist[i, :] = np.sqrt(np.sum((x_train - centroid[i, :]) ** 2, axis=1))   
        membership = np.argmin(dist, axis=0)
        print(membership)

for i in range(k):
    centroid[i, :] = np.mean(x_train[membership == i, :], axis=0)

print("Centroid after " + str(n) + " iterations:")
print(centroid)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[1 1 1 1 1 0 1 2 1 0 2 1 0 1 0 0 0 2 2 1 0 1 0 0 2 0 2 2 0 1 0 1 2 2 0 2 2
 0 1 0 1 2 0 2 1 1 0 1 1 2 1 0 1 1 1 2 0 1 0 1 1 1 2 1 1 0 0 1 0 2 0 0 1 1
 0 2 2 1 2 1 1 1 1 2 1 0 0 1 0 0 0 0 0 0 1 1 1 1 2 2 1 2 1 1 0 1 1 2 2 0 1
 2 0 0 2 1 2 0 0 1]
Centroid after 1 iterations:
[[4.9975     3.415      1.4525     0.235     ]
 [5.92941176 2.77647059 4.4372549  1.44901961]
 [6.84137931 3.06551724 5.72758621 2.07931034]]


In [6]:
dist = np.zeros(shape=(k, x_test.shape[0]))
for i in range(k):
    dist[i] = np.sqrt(np.sum((x_test - centroid[i]) ** 2, axis=1))
membership = np.argmin(dist, axis=0)

print(y_test.astype(int))
print(membership)

[2 0 1 1 2 0 2 2 0 2 1 2 0 2 1 1 0 1 0 1 2 0 0 1 0 1 0 1 2 2]
[2 0 0 0 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 2 0 0 0 0 0 0 0 1 1]
